---
- name: install apps with App Store
  command: "mas install {{ item }}"
  register: result
  changed_when: result.stdout.find('Installed') != 1

- name: update apps with App Store
  command: "mas upgrade {{ item }}"
  register: result
  changed_when: result.stdout.find('Installed') != 1
