---
- name: signs in to App Store
  ansible.builtin.pause:
    prompt: Press Command+C to quit now if you have not already signed in to App Store
    seconds: "{{ macos_pause }}"

- name: installs mas-cli with Homebrew
  homebrew:
    name: "{{ macos_mas_package }}"

- include_tasks: install.yml
  loop: "{{ macos_appstore_apps }}"
